# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/Users/ebak/Desktop/OrangeG.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.
from PyQt5 import QtCore, QtGui, QtWidgets
import json, random, PyQtChart

f = open("questions.json", encoding="utf-8-sig")
phrases = json.load(f)
f.close()

random.shuffle(phrases)


class Ui_MainWindow(object):

    def setupUi(self, MainWindow):
        self.list_of_values = []
        self.n = 0
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 650)
        MainWindow.setStyleSheet("background-color:rgb(71, 71, 71);\n"
"")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.next_button = QtWidgets.QPushButton(self.centralwidget)
        self.next_button.setGeometry(QtCore.QRect(405, 460, 150, 111))
        font = QtGui.QFont()
        font.setFamily("PT Mono")
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        self.next_button.setFont(font)
        self.next_button.setStyleSheet(" QPushButton {\n"
"    background-color: rgb(239, 150, 9);\n"
"border-radius:10px;\n"
" }\n"
"\n"
" QPushButton:pressed {\n"
"     background-color: rgb(225, 117, 0);\n"
" }\n"

"")
        self.next_button.setObjectName("next_button")

        self.score = {"Винни-Пух": 50,
                 "Тигра": 50,
                 "Иа-Иа": 50,
                 "Кристофер Робин": 50,
                 "Крошка Ру": 50,
                 "Пятачок": 50,
                 "Кролик": 50
                 }

        self.next_button.clicked.connect(self.next_fun)


        self.phrase = QtWidgets.QLabel(self.centralwidget)
        self.phrase.setEnabled(True)
        self.phrase.setGeometry(QtCore.QRect(50, 135, 700, 181))
        font = QtGui.QFont()
        font.setFamily("PT Mono")
        font.setPointSize(18)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.phrase.setFont(font)
        self.phrase.setAutoFillBackground(False)
        self.phrase.setStyleSheet("background-color: rgb(239, 150, 9);\n"
"border-radius:10px")
        self.phrase.setAlignment(QtCore.Qt.AlignCenter)
        self.phrase.setObjectName("phrase")
        self.choose = QtWidgets.QSlider(self.centralwidget)
        self.choose.setMinimum(-3)
        self.choose.setMaximum(3)
        self.choose.setValue(0)
        self.choose.setTickInterval(1)
        self.choose.setGeometry(QtCore.QRect(180, 360, 401, 41))
        self.choose.setStyleSheet("background-color:rgb(239, 150, 9);\n"
"border-radius:10px")
        self.choose.setOrientation(QtCore.Qt.Horizontal)
        self.choose.setObjectName("choose")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(0, 10, 800, 51))
        font = QtGui.QFont()
        font.setFamily("PT Mono")
        font.setBold(True)
        font.setWeight(75)
        self.tabWidget.setFont(font)
        self.tabWidget.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.tabWidget.setAutoFillBackground(False)
        self.tabWidget.setStyleSheet("background-color:  rgb(239, 150, 9);")
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.tabWidget.addTab(self.tab_2, "")
        self.disagree = QtWidgets.QLabel(self.centralwidget)
        self.disagree.setGeometry(QtCore.QRect(50, 400, 100, 60))
        font = QtGui.QFont()
        font.setFamily("PT Mono")
        font.setBold(True)
        font.setWeight(75)
        self.disagree.setFont(font)
        self.disagree.setStyleSheet("background-color:  rgb(239, 150, 9);\n"
"border-radius:10px;")
        self.disagree.setAlignment(QtCore.Qt.AlignCenter)
        self.disagree.setObjectName("disagree")
        self.agree = QtWidgets.QLabel(self.centralwidget)
        self.agree.setGeometry(QtCore.QRect(650, 400, 100, 60))
        font = QtGui.QFont()
        font.setFamily("PT Mono")
        font.setBold(True)
        font.setWeight(75)
        self.agree.setFont(font)
        self.agree.setStyleSheet("background-color : rgb(239, 150, 9);\n"
"border-radius:10px;")
        self.agree.setAlignment(QtCore.Qt.AlignCenter)
        self.agree.setObjectName("agree")
        self.back_button = QtWidgets.QPushButton(self.centralwidget)
        self.back_button.setGeometry(QtCore.QRect(245, 460, 150, 111))
        font = QtGui.QFont()
        font.setFamily("PT Mono")
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        self.back_button.setFont(font)
        self.back_button.setStyleSheet(" QPushButton {"
"    background-color: rgb(239, 150, 9);"
"border-radius:10px;"
" }"
" QPushButton:pressed {"
"     background-color: rgb(225, 117, 0);"
" }"
)
        self.back_button.setObjectName("back_button")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0) # 0-Тест 1-Редактор

        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.next_button.setText(_translate("MainWindow", "Дальше"))
        self.phrase.setText(_translate("MainWindow", phrases[0]["question"]))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Тест"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Редактор"))
        self.disagree.setText(_translate("MainWindow", "Не согласен"))
        self.agree.setText(_translate("MainWindow", "Согласен"))
        self.back_button.setText(_translate("MainWindow", "Назад"))
        self.back_button.clicked.connect(self.back_fun)

    def pointer(self, vall, index):

        for i in range(len(phrases[index]["characters"])):
                hero = phrases[index]["characters"][i]
                self.score[hero] += vall * 3
        if len(self.list_of_values) - 1 >= index: # correcting the old value
                self.score[hero] -= self.list_of_values[index] * 3
                self.list_of_values[index] = vall
        else:
            self.list_of_values.append(vall)

    def finish(self):
        self.finish_list=[(value,key) for key,value in self.score.items()]
        self.finish_list.sort(reverse=True)
        if self.finish_list[0][0]==self.finish_list[1][0]:
            self.phrase.setText("У Вас одинаково выражены два или более психотипа, которые\nхарактерны для персонажей сказки «Винни-Пух». Возможно, что\nу Вас одинаковое соотношение всех имеющихся психотипов. \nВозможен также вариант, что Вы просто ответили на вопросы таким образом,\n что Вы оказались на грани результатов, \nхотя на самом деле у Вас есть определенный \nпсихотип среди имеющихся персонажей.\n Мы не можем с точностью ответить, \nприсущи Вам черты всех персонажей или \nВы просто случайно получили такой результат. \nСоответственно, мы не можем предоставить более \nдетальное описание Вашей личности. \nОднако Вы можете рассмотреть таблицу с результатами\n и определить, личность какого персонажа набрала \nнаибольшее количество процентов.")
            self.phrase.adjustSize()
            MainWindow.sizeHint()
        else:
            self.phrase.setText("Поздравляю!\nВы "+max(self.finish_list)[1])
        self.init_game()
        self.next_button.deleteLater()
        self.back_button.deleteLater()
        self.agree.deleteLater()
        self.disagree.deleteLater()
        self.choose.deleteLater()


    def init_game(self):
        self.test_button = QtWidgets.QPushButton(self.centralwidget)
        self.test_button.setGeometry(QtCore.QRect(300, 500, 200, 150))
        self.test_button.setStyleSheet(" QPushButton {"
                                       "    background-color: rgb(239, 150, 9);"
                                       "border-radius:10px;"
                                       " }"
                                       " QPushButton:pressed {"
                                       "     background-color: rgb(225, 117, 0);"
                                       " }"
                                       )
        self.test_button.show()


            
    def next_fun(self):
        self.pointer(self.choose.value(), self.n)
        self.n += 1
        self.phrase.setText(phrases[self.n]["question"])
        if len(self.list_of_values) - 1 >= self.n:
            self.choose.setValue(self.list_of_values[self.n])
        else:
            self.choose.setValue(0)
        if self.n == 32:
            self.finish()




    def back_fun(self):
        if self.n == 0:
            pass
        else:
            self.n -= 1
            self.phrase.setText(phrases[self.n]["question"])
            self.choose.setValue(self.list_of_values[self.n])


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
